name: 'Quality'

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🔮 Install Composer Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: 🕵️‍♂️ Run Laravel Pint
        run: composer lint -- --test

  composer:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🕵️‍♂️ Run Composer Validate
        run: composer validate
      - name: 🕵️‍♂️ Run Composer Audit
        run: composer audit
